[package]
# Don't forget to rename `rusty-dll` to your project name!
# To build to x86 targets you can use `--target i686-pc-windows-msvc`
name = "rusty-dll"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
